name: 🤖New dataset
description: Add a new dataset to MTEB
title: "dataset: "
labels: ["new dataset"]
body:
  - type: textarea
    attributes:
      label: Link to the issue
      description: Please provide a link to the issue that this PR is fixing. If this PR is not related to an issue, please leave this field empty.
      value: "fix: "
  - type: textarea
    attributes:
      label: Describe PR
      description: A clear and concise description of the PR, as well as what you expected to happen when encountering it.
    validations:
      required: true