name: 🤖New dataset
description: Create a request for a new dataset to be added to MTEB
title: "dataset: "
labels: ["new dataset"]
body:
  - type: textarea
    attributes:
      label: dataset link on Hugging dataset
      description: Please provide a link to the dataset on Hugging Face.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Arxiv link
      description: If the dataset is based on a paper, please provide a link to the paper on Arxiv or another academic repository.
