name: 🤖New model
description: Create a request for a new model to be added to MTEB
title: "model: "
labels: ["new model"]
body:
  - type: textarea
    attributes:
      label: Model link on Hugging Face
      description: Please provide a link to the model on Hugging Face. If the model is closed-source, please provide a link to the model provider or documentation.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Arxiv link
      description: If the model is based on a paper, please provide a link to the paper on Arxiv or another academic repository.
